// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddzvobqntettqmxqxpks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkenZvYnFudGV0dHFteHF4cGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTA3NTQsImV4cCI6MjA3MDc2Njc1NH0.0ke2PPTATfdgwTYSuGXRn8PA4ls7PangXVVs7i9jg3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});